#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99

EXEC="sh /usr/wan_ip.sh &"

start_service() {
  procd_open_instance
  procd_set_param command $EXEC
  procd_set_param respawn
  procd_close_instance
}

start() {
        service_start $EXEC
}

stop() {
        service_stop $EXEC
}

reload() {
        service_reload $EXEC
}
